# Generated by Django 6.0.5 on 2026-05-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('calorias_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('proteinas_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbohidratos_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grasas_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fibra_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('es_peruano', models.BooleanField(default=False)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alimentos',
                'ordering': ['nombre'],
            },
        ),
    ]
