# Generated by Django 6.0.5 on 2026-05-08 05:37

import django.db.models.deletion
import nutricion.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('icono', models.CharField(max_length=50)),
                ('condicion', models.JSONField()),
            ],
            options={
                'db_table': 'logros',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[nutricion.validators.validar_cantidad_positiva])),
                ('talla_cm', models.IntegerField(validators=[nutricion.validators.validar_cantidad_positiva])),
                ('edad', models.IntegerField(validators=[nutricion.validators.validar_cantidad_positiva])),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('nivel_actividad', models.CharField(choices=[('SE', 'Sedentario'), ('LI', 'Ligero'), ('MO', 'Moderado'), ('IN', 'Intenso'), ('MI', 'Muy intenso')], max_length=2)),
                ('objetivo', models.CharField(choices=[('PP', 'Perder peso'), ('MA', 'Mantener peso'), ('GM', 'Ganar masa muscular')], max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'perfiles_usuarios',
            },
        ),
        migrations.CreateModel(
            name='MetaNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_meta', models.IntegerField()),
                ('proteinas_g', models.IntegerField()),
                ('carbohidratos_g', models.IntegerField()),
                ('grasas_g', models.IntegerField()),
                ('agua_ml', models.IntegerField(default=2000)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='nutricion.perfilusuario')),
            ],
            options={
                'verbose_name': 'Meta Nutricional',
                'verbose_name_plural': 'Metas Nutricionales',
                'db_table': 'metas_nutricionales',
            },
        ),
        migrations.CreateModel(
            name='RegistroComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_comida', models.CharField(choices=[('DE', 'Desayuno'), ('AL', 'Almuerzo'), ('CE', 'Cena'), ('SN', 'Snack')], max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Comida',
                'verbose_name_plural': 'Registros de Comidas',
                'db_table': 'registros_comidas',
                'ordering': ['-fecha', 'tipo_comida'],
                'unique_together': {('usuario', 'fecha', 'tipo_comida')},
            },
        ),
        migrations.CreateModel(
            name='ItemRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_g', models.DecimalField(decimal_places=2, max_digits=7, validators=[nutricion.validators.validar_cantidad_positiva])),
                ('total_calorias', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_proteinas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_carbohidratos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_grasas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alimentos.alimento')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutricion.registrocomida')),
            ],
            options={
                'verbose_name': 'Ítem de Registro',
                'verbose_name_plural': 'Ítems de Registros',
                'db_table': 'items_registros',
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logros_usuarios',
                'unique_together': {('usuario', 'logro')},
            },
        ),
        migrations.CreateModel(
            name='RegistroHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vasos_agua', models.IntegerField(default=0)),
                ('horas_sueno', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('pasos', models.IntegerField(default=0)),
                ('minutos_ejercicio', models.IntegerField(default=0)),
                ('tipo_ejercicio', models.CharField(blank=True, choices=[('CA', 'Cardio'), ('FU', 'Fuerza'), ('YO', 'Yoga'), ('CM', 'Caminata'), ('OT', 'Otro')], max_length=2, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Hábito',
                'verbose_name_plural': 'Registros de Hábitos',
                'db_table': 'registros_habitos',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
